# Generated by Django 4.2.5 on 2023-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KunlikNewuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('autor', models.CharField(max_length=255)),
            ],
        ),
    ]
